# Generated by Django 4.1.7 on 2023-04-28 04:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_of_registration',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
